name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _anaconda_depends=5.3.1=py37_1
  - _ipyw_jlab_nb_ext_conf=0.1.0=py37_0
  - _libgcc_mutex=0.1=main
  - alabaster=0.7.12=py_0
  - anaconda=custom=py37_1
  - anaconda-client=1.7.2=py_0
  - anaconda-navigator=1.9.7=py37_0
  - anaconda-project=0.8.3=py_0
  - appdirs=1.4.3=py_1
  - argh=0.26.2=py37_1001
  - asn1crypto=1.3.0=py37_0
  - astroid=2.3.3=py37_0
  - astropy=4.0=py37h516909a_0
  - atomicwrites=1.3.0=py_0
  - attrs=19.3.0=py_0
  - automat=0.8.0=py_0
  - autopep8=1.4.4=py_0
  - babel=2.8.0=py_0
  - backcall=0.1.0=py_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - backports.os=0.1.1=py37_0
  - backports.shutil_get_terminal_size=1.0.0=py_3
  - backports.tempfile=1.0=py_1
  - backports.weakref=1.0.post1=py_1
  - bcrypt=3.1.7=py37h516909a_0
  - beautifulsoup4=4.7.1=py37_1000
  - bitarray=1.2.1=py37h516909a_0
  - bkcharts=0.2=py37_0
  - blas=1.0=mkl
  - blaze=0.11.3=py37_0
  - bleach=3.1.0=py_0
  - blosc=1.16.3=hd408876_0
  - bokeh=1.4.0=py37_0
  - boto=2.49.0=py_0
  - bottleneck=1.3.1=py37hc1659b7_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.14.12=h8948797_3
  - cartopy=0.17.0=py37h4331854_1006
  - certifi=2019.11.28=py37_0
  - cffi=1.13.2=py37h8022711_0
  - chardet=3.0.4=py37_1003
  - click=7.0=py_0
  - cloudpickle=1.2.2=py_1
  - clyent=1.2.2=py_1
  - colorama=0.4.3=py_0
  - conda=4.8.1=py37_0
  - conda-build=3.15.1=py37_0
  - conda-env=2.6.0=h36134e3_1
  - conda-package-handling=1.6.0=py37h516909a_1
  - conda-verify=3.1.1=py37_1000
  - constantly=15.1.0=py_0
  - contextlib2=0.6.0.post1=py_0
  - cryptography=2.8=py37h72c5cf5_1
  - curl=7.65.3=hf8cf82a_0
  - cycler=0.10.0=py_2
  - cython=0.29.14=py37he1b5a44_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask=2.9.1=py_0
  - dask-core=2.9.1=py_0
  - datashape=0.5.4=py_1
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - diff-match-patch=20181111=py_0
  - distributed=2.9.1=py_0
  - docutils=0.16=py37_0
  - entrypoints=0.3=py37_1000
  - et_xmlfile=1.0.1=py_1001
  - expat=2.2.6=he6710b0_0
  - fastcache=1.1.0=py37h516909a_0
  - ffmpeg=4.2=h1a5d6f3_0
  - filelock=3.0.10=py_0
  - flake8=3.7.9=py37_0
  - flask=1.1.1=py_1
  - flask-cors=3.0.8=py_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.10.0=he983fc9_1
  - fribidi=1.0.5=h7b6447c_0
  - fsspec=0.6.2=py_0
  - future=0.18.2=py37_0
  - geos=3.7.2=he1b5a44_2
  - get_terminal_size=1.0.0=haa9412d_0
  - gevent=1.4.0=py37h516909a_0
  - glib=2.63.1=h5a9c865_0
  - glob2=0.7=py_0
  - gmp=6.1.2=h6c8ec71_1
  - gmpy2=2.0.8=py37hb20f59a_1002
  - graphite2=1.3.13=h23475e2_0
  - greenlet=0.4.15=py37h516909a_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.5=h36ae1b5_0
  - h5py=2.9.0=nompi_py37hcafd542_1103
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.4=nompi_h3c11f04_1106
  - heapdict=1.0.1=py_0
  - html5lib=1.0.1=py_0
  - hyperlink=17.3.1=py_0
  - icu=58.2=h9c2bf20_1
  - idna=2.8=py37_1000
  - imageio=2.6.1=py37_0
  - imagesize=1.2.0=py_0
  - incremental=17.5.0=py_0
  - intel-openmp=2019.4=243
  - intervaltree=3.0.2=py_0
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.11.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - ipywidgets=7.5.1=py_0
  - isort=4.3.21=py37_0
  - itsdangerous=1.1.0=py_0
  - jbig=2.1=hdba287a_0
  - jdcal=1.4.1=py_0
  - jedi=0.15.2=py37_0
  - jeepney=0.4.2=py_0
  - jinja2=2.10.3=py_0
  - joblib=0.14.1=py_0
  - jpeg=9b=h024ee3a_2
  - json5=0.8.5=py_0
  - jsonschema=2.6.0=py37_1002
  - jupyter=1.0.0=py_2
  - jupyter_client=5.3.4=py37_1
  - jupyter_console=6.0.0=py_0
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=0.35.6=py37_0
  - jupyterlab_launcher=0.13.1=py_2
  - jupyterlab_server=0.2.0=py_0
  - keyring=19.2.0=py37_0
  - kiwisolver=1.1.0=py37hc9558a2_0
  - krb5=1.16.4=h173b8e3_0
  - lame=3.100=h7b6447c_0
  - lazy-object-proxy=1.4.3=py37h516909a_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libcurl=7.65.3=hda55be3_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - liblief=0.9.0=h7725739_2
  - libllvm8=8.0.1=hc9558a2_0
  - libopus=1.3=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libspatialindex=1.9.3=he6710b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libtool=2.4.6=h7b6447c_5
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=hea5a465_1
  - libxslt=1.1.33=h7d1a2b0_0
  - llvmlite=0.31.0=py37h8b12597_0
  - locket=0.2.0=py_2
  - lxml=4.4.1=py37h7ec2d77_0
  - lz4-c=1.8.1.2=h14c3975_0
  - lzo=2.10=h49e0be7_2
  - markupsafe=1.1.1=py37h516909a_0
  - matplotlib=2.2.2=py37hb69df0a_2
  - mccabe=0.6.1=py_1
  - mistune=0.8.4=py37h516909a_1000
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37h516909a_0
  - mkl_fft=1.0.15=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - more-itertools=8.0.2=py_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.1=hdf1c602_3
  - mpmath=1.1.0=py_0
  - msgpack-python=0.6.2=py37hc9558a2_0
  - multipledispatch=0.6.0=py_0
  - navigator-updater=0.2.1=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3=py_0
  - ncurses=6.1=he6710b0_1
  - networkx=2.4=py_0
  - nltk=3.4.4=py_0
  - nose=1.3.7=py37_1003
  - notebook=6.0.1=py37_0
  - numba=0.47.0=py37hb3f55d8_0
  - numexpr=2.7.1=py37hb3f55d8_0
  - numpy=1.17.4=py37hc1035e2_0
  - numpy-base=1.17.4=py37hde5b4d6_0
  - numpydoc=0.9.2=py_0
  - odo=0.5.1=py_1
  - olefile=0.46=py_0
  - openh264=1.8.0=hd408876_0
  - openpyxl=3.0.3=py_0
  - openssl=1.1.1d=h516909a_0
  - owslib=0.19.0=py_2
  - packaging=20.0=py_0
  - pandas=0.25.3=py37hb3f55d8_0
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py_1
  - pango=1.40.14=he752989_2
  - parso=0.5.2=py_0
  - partd=1.1.0=py_0
  - patchelf=0.10=he6710b0_0
  - path.py=11.0.1=py_0
  - pathlib2=2.3.5=py37_0
  - pathtools=0.1.2=py_1
  - patsy=0.5.1=py_0
  - pcre=8.43=he6710b0_0
  - pep8=1.7.1=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pillow=7.0.0=py37hb39fc2d_0
  - pip=19.3.1=py37_0
  - pixman=0.38.0=h516909a_1003
  - pkginfo=1.5.0.1=py_0
  - pluggy=0.11.0=py_0
  - ply=3.11=py_1
  - proj4=6.1.1=hc80f0dc_1
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=2.0.10=py_0
  - psutil=5.6.7=py37h516909a_0
  - pthread-stubs=0.4=h14c3975_1001
  - ptyprocess=0.6.0=py_1001
  - py=1.8.1=py_0
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycodestyle=2.5.0=py_0
  - pycosat=0.6.3=py37h516909a_1002
  - pycparser=2.19=py37_1
  - pycrypto=2.6.1=py37h516909a_1003
  - pycurl=7.43.0.4=py37h16ce93b_0
  - pydocstyle=4.0.1=py_0
  - pyepsg=0.4.0=py_0
  - pyflakes=2.1.1=py_0
  - pygments=2.5.2=py_0
  - pyhamcrest=1.9.0=py_2
  - pykdtree=1.3.1=py37hc1659b7_1002
  - pylint=2.4.4=py37_0
  - pyodbc=4.0.28=py37he1b5a44_0
  - pyopenssl=19.1.0=py37_0
  - pyparsing=2.4.6=py_0
  - pyproj=2.3.1=py37h2fd02e8_0
  - pyqt=5.6.0=py37h13b7fb3_1008
  - pyshp=2.1.0=py_0
  - pysocks=1.7.1=py37_0
  - pytables=3.5.1=py37h5d69a80_0
  - pytest=4.5.0=py37_0
  - pytest-arraydiff=0.3=py37h39e3cac_0
  - pytest-astropy=0.6.0=py_0
  - pytest-astropy-header=0.1.1=py_0
  - pytest-doctestplus=0.5.0=py_0
  - pytest-openfiles=0.4.0=py_0
  - pytest-remotedata=0.3.2=py37_0
  - python=3.7.6=h0371630_2
  - python-dateutil=2.8.1=py_0
  - python-jsonrpc-server=0.3.2=py_0
  - python-language-server=0.31.2=py37_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyxdg=0.26=py_0
  - pyyaml=5.1.2=py37h516909a_0
  - pyzmq=18.0.2=py37hc4ba49a_0
  - qdarkstyle=2.7=py_0
  - qt=5.6.3=h8bf5577_3
  - qtawesome=0.6.1=py_0
  - qtconsole=4.6.0=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - ripgrep=11.0.2=he32d670_0
  - rope=0.16.0=py_0
  - ruamel_yaml=0.15.71=py37h14c3975_1000
  - scikit-image=0.14.2=py37hf484d3e_0
  - scikit-learn=0.22.1=py37hd81dba3_0
  - scipy=1.3.2=py37h7c811a0_0
  - seaborn=0.9.0=py_0
  - secretstorage=3.1.2=py37_0
  - send2trash=1.5.0=py_0
  - service_identity=18.1.0=py_0
  - setuptools=45.0.0=py37_1
  - shapely=1.6.4=py37hec07ddf_1006
  - simplegeneric=0.8.1=py_1
  - singledispatch=3.4.0.3=py37_1000
  - sip=4.18.1=py37hf484d3e_1000
  - six=1.14.0=py37_0
  - snappy=1.1.7=hbae5bb6_3
  - snowballstemmer=2.0.0=py_0
  - sortedcollections=1.1.2=py_0
  - sortedcontainers=2.1.0=py_0
  - sphinx=2.3.1=py_0
  - sphinxcontrib=1.0=py37_1
  - sphinxcontrib-applehelp=1.0.1=py_0
  - sphinxcontrib-devhelp=1.0.1=py_0
  - sphinxcontrib-htmlhelp=1.0.2=py_0
  - sphinxcontrib-jsmath=1.0.1=py_0
  - sphinxcontrib-qthelp=1.0.2=py_0
  - sphinxcontrib-serializinghtml=1.1.3=py_0
  - sphinxcontrib-websupport=1.1.2=py_0
  - spyder=3.3.2=py37_1001
  - spyder-kernels=0.2.6=py_1
  - sqlalchemy=1.3.12=py37h516909a_0
  - sqlite=3.30.1=h7b6447c_0
  - statsmodels=0.10.2=py37hc1659b7_0
  - sympy=1.5.1=py37_0
  - tbb=2019.8=hfd86e86_0
  - tblib=1.6.0=py_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.41.1=py_0
  - traitlets=4.3.3=py37_0
  - twisted=19.10.0=py37h516909a_0
  - typing=3.6.4=py37_0
  - ujson=1.35=py37h516909a_1001
  - unicodecsv=0.14.1=py_1
  - unixodbc=2.3.7=h14c3975_0
  - watchdog=0.9.0=py37_1
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h516909a_0
  - x264=1!152.20180806=h7b6447c_0
  - xarray=0.14.1=py_1
  - xlrd=1.2.0=py_0
  - xlsxwriter=1.2.7=py_0
  - xlwt=1.3.0=py_1
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - yapf=0.28.0=py_0
  - zeromq=4.3.1=he6710b0_3
  - zict=1.0.0=py_0
  - zipp=0.6.0=py_0
  - zlib=1.2.11=h7b6447c_3
  - zope=1.0=py37_1
  - zope.interface=4.7.1=py37h516909a_0
  - zstd=1.3.7=h0b5b093_0
prefix: /usr/local/anaconda3

